# SQL Assignment : Filtering and Sorting

In [4]:
import mysql.connector as connection
try:
    mydb = connection.connect(host = "localhost",user = "root",passwd = "Diksha@2004",use_pure = True)
    print (mydb.is_connected())

    query = "Create database skills;"
    cursor = mydb.cursor()
    cursor.execute(query)
    print("Database created!")
    mydb.close()

except Exception as e:
    print(str(e))

True
1007 (HY000): Can't create database 'skills'; database exists

In [5]:
import mysql.connector
conn = mysql.connector.connect(host = "localhost", user = "root",passwd = "Diksha@2004", database = "skills")
cursor = conn.cursor()

In [8]:
cursor.execute("SHOW TABLES")
tables = cursor.fetchall()
for t in tables:
    print(t)

('employees',)

In [9]:
cursor.execute("SELECT * FROM employees")
rows = cursor.fetchall()
for row in rows:
    print(row)

(101, 'Rahul Mehta', 'Sales', 'Delhi', 55000, '2020-04-12')
(102, 'Priya Sharma', 'HR', 'Mumbai', 62000, '2019-09-25')
(103, 'Aman Singh', 'IT', 'Bengaluru', 72000, '2021-03-10')
(104, 'Neha Patel', 'Sales', 'Delhi', 48000, '2022-01-14')
(105, 'Karan Joshi', 'Marketing', 'Pune', 45000, '2018-07-22')
(106, 'Divya Nair', 'IT', 'Chennai', 81000, '2019-12-11')
(107, 'Raj Kumar', 'HR', 'Delhi', 60000, '2020-05-28')
(108, 'Simran Kaur', 'Finance', 'Mumbai', 58000, '2021-08-03')
(109, 'Arjun Reddy', 'IT', 'Hyderabad', 70000, '2022-02-18')
(110, 'Anjali Das', 'Sales', 'Kolkata', 51000, '2023-01-15')

In [10]:
import pandas as pd
df = pd.read_sql("SELECT * FROM employees",conn)
df

C:\Users\Diksha\AppData\Local\Temp\ipykernel_12512\1948842817.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM employees",conn)

   EmpId       EmpName Department       city  Salary    HireDate
0    101   Rahul Mehta      Sales      Delhi   55000  2020-04-12
1    102  Priya Sharma         HR     Mumbai   62000  2019-09-25
2    103    Aman Singh         IT  Bengaluru   72000  2021-03-10
3    104    Neha Patel      Sales      Delhi   48000  2022-01-14
4    105   Karan Joshi  Marketing       Pune   45000  2018-07-22
5    106    Divya Nair         IT    Chennai   81000  2019-12-11
6    107     Raj Kumar         HR      Delhi   60000  2020-05-28
7    108   Simran Kaur    Finance     Mumbai   58000  2021-08-03
8    109   Arjun Reddy         IT  Hyderabad   70000  2022-02-18
9    110    Anjali Das      Sales    Kolkata   51000  2023-01-15

In [16]:
# Question 1 : Show employees working in either the ‘IT’ or ‘HR’ departments.
df_it_hr = pd.read_sql("SELECT * FROM Employees WHERE Department IN ('IT','HR')", conn)
df_it_hr

C:\Users\Diksha\AppData\Local\Temp\ipykernel_12512\2048610174.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_it_hr = pd.read_sql("SELECT * FROM Employees WHERE Department IN ('IT','HR')", conn)

   EmpId       EmpName Department       city  Salary    HireDate
0    102  Priya Sharma         HR     Mumbai   62000  2019-09-25
1    103    Aman Singh         IT  Bengaluru   72000  2021-03-10
2    106    Divya Nair         IT    Chennai   81000  2019-12-11
3    107     Raj Kumar         HR      Delhi   60000  2020-05-28
4    109   Arjun Reddy         IT  Hyderabad   70000  2022-02-18

In [17]:
# Question 2: Employees in Sales, IT, or Finance departments
df_sales_it_finance = pd.read_sql(
    "SELECT * FROM Employees WHERE Department IN ('Sales', 'IT', 'Finance')",
    conn
)
df_sales_it_finance

C:\Users\Diksha\AppData\Local\Temp\ipykernel_12512\2054645517.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sales_it_finance = pd.read_sql(

   EmpId      EmpName Department       city  Salary    HireDate
0    101  Rahul Mehta      Sales      Delhi   55000  2020-04-12
1    103   Aman Singh         IT  Bengaluru   72000  2021-03-10
2    104   Neha Patel      Sales      Delhi   48000  2022-01-14
3    106   Divya Nair         IT    Chennai   81000  2019-12-11
4    108  Simran Kaur    Finance     Mumbai   58000  2021-08-03
5    109  Arjun Reddy         IT  Hyderabad   70000  2022-02-18
6    110   Anjali Das      Sales    Kolkata   51000  2023-01-15

In [18]:
# Question 3: Employees with salary between 50,000 and 70,000
df_salary_range = pd.read_sql(
    "SELECT * FROM Employees WHERE Salary BETWEEN 50000 AND 70000",
    conn
)
df_salary_range

C:\Users\Diksha\AppData\Local\Temp\ipykernel_12512\3792151589.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_salary_range = pd.read_sql(

   EmpId       EmpName Department       city  Salary    HireDate
0    101   Rahul Mehta      Sales      Delhi   55000  2020-04-12
1    102  Priya Sharma         HR     Mumbai   62000  2019-09-25
2    107     Raj Kumar         HR      Delhi   60000  2020-05-28
3    108   Simran Kaur    Finance     Mumbai   58000  2021-08-03
4    109   Arjun Reddy         IT  Hyderabad   70000  2022-02-18
5    110    Anjali Das      Sales    Kolkata   51000  2023-01-15

In [19]:
# Question 4: Employees whose names start with 'A'
df_name_a = pd.read_sql(
    "SELECT * FROM Employees WHERE EmpName LIKE 'A%'",
    conn
)
df_name_a

C:\Users\Diksha\AppData\Local\Temp\ipykernel_12512\3793949492.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_name_a = pd.read_sql(

   EmpId      EmpName Department       city  Salary    HireDate
0    103   Aman Singh         IT  Bengaluru   72000  2021-03-10
1    109  Arjun Reddy         IT  Hyderabad   70000  2022-02-18
2    110   Anjali Das      Sales    Kolkata   51000  2023-01-15

In [20]:
# Question 5: Employees whose names contain 'an'
df_name_an = pd.read_sql(
    "SELECT * FROM Employees WHERE EmpName LIKE '%an%'",
    conn
)
df_name_an

C:\Users\Diksha\AppData\Local\Temp\ipykernel_12512\2657924513.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_name_an = pd.read_sql(

   EmpId      EmpName Department       city  Salary    HireDate
0    103   Aman Singh         IT  Bengaluru   72000  2021-03-10
1    105  Karan Joshi  Marketing       Pune   45000  2018-07-22
2    108  Simran Kaur    Finance     Mumbai   58000  2021-08-03
3    110   Anjali Das      Sales    Kolkata   51000  2023-01-15

In [21]:
# Question 6: Employees from Delhi or Mumbai with salary > 55000
df_delhi_mumbai = pd.read_sql(
    "SELECT * FROM Employees WHERE (City IN ('Delhi','Mumbai')) AND Salary > 55000",
    conn
)
df_delhi_mumbai

C:\Users\Diksha\AppData\Local\Temp\ipykernel_12512\2627662022.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_delhi_mumbai = pd.read_sql(

   EmpId       EmpName Department    city  Salary    HireDate
0    102  Priya Sharma         HR  Mumbai   62000  2019-09-25
1    107     Raj Kumar         HR   Delhi   60000  2020-05-28
2    108   Simran Kaur    Finance  Mumbai   58000  2021-08-03

In [22]:
# Question 7: All employees except those from HR department
df_not_hr = pd.read_sql(
    "SELECT * FROM Employees WHERE Department <> 'HR'",
    conn
)
df_not_hr

C:\Users\Diksha\AppData\Local\Temp\ipykernel_12512\1374732623.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_not_hr = pd.read_sql(

   EmpId      EmpName Department       city  Salary    HireDate
0    101  Rahul Mehta      Sales      Delhi   55000  2020-04-12
1    103   Aman Singh         IT  Bengaluru   72000  2021-03-10
2    104   Neha Patel      Sales      Delhi   48000  2022-01-14
3    105  Karan Joshi  Marketing       Pune   45000  2018-07-22
4    106   Divya Nair         IT    Chennai   81000  2019-12-11
5    108  Simran Kaur    Finance     Mumbai   58000  2021-08-03
6    109  Arjun Reddy         IT  Hyderabad   70000  2022-02-18
7    110   Anjali Das      Sales    Kolkata   51000  2023-01-15

In [23]:
# Question 8: Employees hired between 2019 and 2022, ordered by HireDate
df_hiredate = pd.read_sql(
    "SELECT * FROM Employees WHERE HireDate BETWEEN '2019-01-01' AND '2022-12-31' ORDER BY HireDate ASC",
    conn
)
df_hiredate

C:\Users\Diksha\AppData\Local\Temp\ipykernel_12512\1435891515.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_hiredate = pd.read_sql(

   EmpId       EmpName Department       city  Salary    HireDate
0    102  Priya Sharma         HR     Mumbai   62000  2019-09-25
1    106    Divya Nair         IT    Chennai   81000  2019-12-11
2    101   Rahul Mehta      Sales      Delhi   55000  2020-04-12
3    107     Raj Kumar         HR      Delhi   60000  2020-05-28
4    103    Aman Singh         IT  Bengaluru   72000  2021-03-10
5    108   Simran Kaur    Finance     Mumbai   58000  2021-08-03
6    104    Neha Patel      Sales      Delhi   48000  2022-01-14
7    109   Arjun Reddy         IT  Hyderabad   70000  2022-02-18